## Functions

In [19]:
import tensorflow as tf

### Reshape

Reshapes a tensor.

```
tf.reshape(
    tensor, shape, name=None
)
```

In [22]:
t1 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t1.numpy())

t2 = tf.reshape(t1, [6])
print(t2.numpy())

t3 = tf.reshape(t2, [3, 2])
print(t3.numpy())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


### Range

Creates a sequence of numbers.

```
tf.range(limit, delta=1, dtype=None, name='range')
tf.range(start, limit, delta=1, dtype=None, name='range')
```

In [23]:
start = 3
limit = 1
delta = -0.5
tf.range(start, limit, delta)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>

## Layers

In [9]:
import tensorflow as tf

### Dense

```
tf.keras.layers.Dense(
    units, activation=None, use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros', kernel_regularizer=None,
    bias_regularizer=None, activity_regularizer=None, kernel_constraint=None,
    bias_constraint=None, **kwargs
)
```

### Conv2D

```
tf.keras.layers.Conv2D(
    filters, kernel_size, strides=(1, 1), padding='valid',
    data_format=None, dilation_rate=(1, 1), groups=1, activation=None,
    use_bias=True, kernel_initializer='glorot_uniform',
    bias_initializer='zeros', kernel_regularizer=None,
    bias_regularizer=None, activity_regularizer=None, kernel_constraint=None,
    bias_constraint=None, **kwargs
)
```

In [10]:
# The inputs are 28x28 RGB images with `channels_last` and the batch size is 4.
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', 
                           input_shape=input_shape[1:])(x)
print(y.shape)

(4, 26, 26, 2)


### Dropout

The Dropout layer randomly sets input units to 0 with a frequency of rate at each step during training time, which helps prevent overfitting. Inputs not set to $0$ are scaled up by $1/(1 - rate)$ such that the sum over all inputs is unchanged.

```
tf.keras.layers.Dropout(
    rate, noise_shape=None, seed=None, **kwargs
)
```

In [13]:
layer = tf.keras.layers.Dropout(.2, input_shape=(2,))
data = tf.range(0, 10, 1, dtype=tf.float32)
print(data)

outputs = layer(data, training=True)
print(outputs)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)
tf.Tensor([ 0.    1.25  2.5   3.75  0.    6.25  7.5   8.75 10.   11.25], shape=(10,), dtype=float32)


### Activation Layer

```
tf.keras.layers.Activation(
    activation, **kwargs
)
```

*Activation function, such as tf.nn.relu, or string name of built-in activation function, such as "relu".*



## Activation Functions


List of Tensorflow's activation functions: [Module: tf.keras.activations](https://www.tensorflow.org/api_docs/python/tf/keras/activations)

#### Linear

```
tf.keras.activations.linear(
    x
)
```

#### ReLU

```
tf.keras.activations.relu(
    x, alpha=0.0, max_value=None, threshold=0.0
)
```

#### Sigmoid

```
tf.keras.activations.sigmoid(
    x
)
```

#### Softmax

```
tf.keras.activations.softmax(
    x, axis=-1
)
```
The axis argument sets which axis of the input the function is applied along.

## Define Network

In [1]:
layers = [Dense(2)]
model = Sequential(layers)

NameError: ignored

In [ ]:
model = Sequential()
model.add(Dense(5, input_dim=2))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('sigmoid'))

##  Compile Network

In [2]:
model.compile(optimizer=✬sgd✬, loss=✬mean_squared_error✬)

SyntaxError: ignored

In [3]:
lgorithm = SGD(lr=0.1, momentum=0.3)
model.compile(optimizer=algorithm, loss=✬mean_squared_error✬)

SyntaxError: ignored

The most common optimization algorithm is stochastic gradient descent, but Keras also
supports a suite of other state-of-the-art optimization algorithms that work well with little or
no configuration. Perhaps the most commonly used optimization algorithms because of their
generally better performance are:

❼ Stochastic Gradient Descent, or sgd, that requires the tuning of a learning rate and
momentum.

❼ Adam, or adam, that requires the tuning of learning rate.

❼ RMSprop, or rmsprop, that requires the tuning of learning rate.


## Fit Network

In [4]:
history = model.fit(X, y, batch_size=10, epochs=100, verbose=0)

NameError: ignored

# Save Model

In [5]:
model.save(✬final_model.h5✬)

SyntaxError: ignored

# Load Model

In [7]:
rom keras.models import load_model
model = load_model(✬final_model.h5✬)

SyntaxError: ignored

# Evaluate Network

In [6]:
loss, accuracy = model.evaluate(X, y)

NameError: ignored

## Make Predictions

In [ ]:
predictions = model.predict(X)

In [8]:
predictions = model.predict_classes(X)

NameError: ignored