## tf Functions

In [2]:
import tensorflow as tf

tf.zeros

tf.ones

### Reshape

Reshapes a tensor.

```
tf.reshape(
    tensor, shape, name=None
)
```

In [ ]:
t1 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t1.numpy())

t2 = tf.reshape(t1, [6])
print(t2.numpy())

t3 = tf.reshape(t2, [3, 2])
print(t3.numpy())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


### Range

Creates a sequence of numbers.

```
tf.range(limit, delta=1, dtype=None, name='range')
tf.range(start, limit, delta=1, dtype=None, name='range')
```

*Creates a sequence of numbers that begins at `start` and extends by increments of `delta` up to but not including `limit`.*

In [ ]:
start = 3
limit = 1
delta = -0.5
tf.range(start, limit, delta)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>

## tf.math

### abs

### add

### Sqrt

## tf.nn

Primitive Neural Net (NN) Operations.



### ReLU

Computes rectified linear: `max(features, 0)`.


```
tf.nn.relu(
    features, name=None
)
```

### Leaky ReLU

Compute the Leaky ReLU activation function.


```
tf.nn.leaky_relu(
    features, alpha=0.2, name=None
)
```

### Softmax

Computes softmax activations.

```
tf.nn.softmax(
    logits, axis=None, name=None
)
```

### Log Softmax

Computes log softmax activations.

```
tf.nn.log_softmax(
    logits, axis=None, name=None
)
```

## tf.random

### Uniform

Outputs random values from a uniform distribution.

```
tf.random.uniform(
    shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None
)
```

### Normal

Outputs random values from a normal distribution.

```
tf.random.normal(
    shape, mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None
)
```

### Gamma

Draws shape samples from each of the given Gamma distribution(s).


```
tf.random.gamma(
    shape, alpha, beta=None, dtype=tf.dtypes.float32, seed=None, name=None
)
```

### Poisson

Draws shape samples from each of the given Poisson distribution(s).

```
tf.random.poisson(
    shape, lam, dtype=tf.dtypes.float32, seed=None, name=None
)
```

### Categorical

Draws samples from a categorical distribution.

```
tf.random.categorical(
    logits, num_samples, dtype=None, seed=None, name=None
)
```

In [ ]:
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]), 5)
samples

<tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[1, 0, 1, 1, 0]])>

### Shuffle

Randomly shuffles a tensor along its first dimension.


```
tf.random.shuffle(
    value, seed=None, name=None
)
```

## tf.optimizers

Public API for tf.keras.optimizers namespace.

For more details: [tf.keras.optimizers](https://www.tensorflow.org/api_docs/python/tf/optimizers)

# tf.keras | Keras

## tf.keras.datasets

List of datasets: [tf.keras.datasets](https://www.tensorflow.org/api_docs/python/tf/keras/datasets)

In [ ]:
mnist = tf.keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## tf.keras.layers

### InputLayer

Layer to be used as an entry point into a Network (a graph of layers).

```
tf.keras.layers.InputLayer(
    input_shape=None, batch_size=None, dtype=None, input_tensor=None, sparse=None,
    name=None, ragged=None, type_spec=None, **kwargs
)
```

It can either wrap an existing tensor (pass an input_tensor argument) or create a placeholder tensor (pass arguments input_shape, and optionally, dtype).

### Dense

```
tf.keras.layers.Dense(
    units, activation=None, use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros', kernel_regularizer=None,
    bias_regularizer=None, activity_regularizer=None, kernel_constraint=None,
    bias_constraint=None, **kwargs
)
```

### Embedding

Turns positive integers (indexes) into dense vectors of fixed size.

```
tf.keras.layers.Embedding(
    input_dim, output_dim, embeddings_initializer='uniform',
    embeddings_regularizer=None, activity_regularizer=None,
    embeddings_constraint=None, mask_zero=False, input_length=None, **kwargs
)
```

### Conv2D

```
tf.keras.layers.Conv2D(
    filters, kernel_size, strides=(1, 1), padding='valid',
    data_format=None, dilation_rate=(1, 1), groups=1, activation=None,
    use_bias=True, kernel_initializer='glorot_uniform',
    bias_initializer='zeros', kernel_regularizer=None,
    bias_regularizer=None, activity_regularizer=None, kernel_constraint=None,
    bias_constraint=None, **kwargs
)
```

In [ ]:
# The inputs are 28x28 RGB images with `channels_last` and the batch size is 4.
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', 
                           input_shape=input_shape[1:])(x)
print(y.shape)

(4, 26, 26, 2)


### Concatenate

Layer that concatenates a list of inputs.


```
tf.keras.layers.Concatenate(
    axis=-1, **kwargs
)
```

In [6]:
x1 = tf.keras.layers.Dense(8)(tf.reshape(tf.range(10), (5,2)))
x2 = tf.keras.layers.Dense(8)(tf.reshape(tf.range(10, 20), (5,2)))
concatted = tf.keras.layers.Concatenate()([x1, x2])
concatted.shape

TensorShape([5, 16])

### Flatten

Flattens the input. Does not affect the batch size.

```
tf.keras.layers.Flatten(
    data_format=None, **kwargs
)
```

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(64, 3, 3, input_shape=(3, 32, 32)))
model.output_shape

(None, 1, 10, 64)

In [ ]:
model.add(tf.keras.layers.Flatten())
model.output_shape

(None, 640)

### Dropout

The Dropout layer randomly sets input units to 0 with a frequency of rate at each step during training time, which helps prevent overfitting. Inputs not set to $0$ are scaled up by $1/(1 - rate)$ such that the sum over all inputs is unchanged.

```
tf.keras.layers.Dropout(
    rate, noise_shape=None, seed=None, **kwargs
)
```

In [ ]:
layer = tf.keras.layers.Dropout(.2, input_shape=(2,))
data = tf.range(0, 10, 1, dtype=tf.float32)
print(data)

outputs = layer(data, training=True)
print(outputs)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)
tf.Tensor([ 0.    1.25  2.5   3.75  0.    6.25  7.5   8.75 10.   11.25], shape=(10,), dtype=float32)


### Activation Layer

```
tf.keras.layers.Activation(
    activation, **kwargs
)
```

*Activation function, such as tf.nn.relu, or string name of built-in activation function, such as "relu".*



### ReLU

Rectified Linear Unit activation function.

```
tf.keras.layers.ReLU(
    max_value=None, negative_slope=0.0, threshold=0.0, **kwargs
)
```

### LeakyReLU

Leaky version of a Rectified Linear Unit.

```
tf.keras.layers.LeakyReLU(
    alpha=0.3, **kwargs
)
```

### Softmax

Softmax activation function.


```
tf.keras.layers.Softmax(
    axis=-1, **kwargs
)
```

## tf.keras.activations


List of Tensorflow's activation functions: [tf.keras.activations](https://www.tensorflow.org/api_docs/python/tf/keras/activations)

#### Linear

```
tf.keras.activations.linear(
    x
)
```

#### ReLU

```
tf.keras.activations.relu(
    x, alpha=0.0, max_value=None, threshold=0.0
)
```

#### Sigmoid

```
tf.keras.activations.sigmoid(
    x
)
```

#### Softmax

```
tf.keras.activations.softmax(
    x, axis=-1
)
```
The axis argument sets which axis of the input the function is applied along.

## tf.keras.optimizers

List of provided otpimizers: [tf.keras.optimizers](https://www.tensorflow.org/api_docs/python/tf/optimizers)

### Optimizer Base Class

```
tf.keras.optimizers.Optimizer(
    name, gradient_aggregator=None, gradient_transformers=None, **kwargs
)
```

### Adam

Optimizer that implements the Adam algorithm.

```
tf.keras.optimizers.Adam(
    learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False,
    name='Adam', **kwargs
)
```

### SGD

Gradient descent (with momentum) optimizer.

```
tf.keras.optimizers.SGD(
    learning_rate=0.01, momentum=0.0, nesterov=False, name='SGD', **kwargs
)
```

### RMSprop

Optimizer that implements the RMSprop algorithm.

```
tf.keras.optimizers.RMSprop(
    learning_rate=0.001, rho=0.9, momentum=0.0, epsilon=1e-07, centered=False,
    name='RMSprop', **kwargs
)
```

## tf.keras.losses

List of all losses: [tf.keras.losses](https://www.tensorflow.org/api_docs/python/tf/keras/losses)

### Classes

#### Loss

Loss base class.

```
tf.keras.losses.Loss(
    reduction=losses_utils.ReductionV2.AUTO, name=None
)
```

#### MeanAbsoluteError

Computes the mean of absolute difference between labels and predictions.


```
tf.keras.losses.MeanAbsoluteError(
    reduction=losses_utils.ReductionV2.AUTO, name='mean_absolute_error'
)
```

In [ ]:
y_true = [[0., 1.], [0., 0.]]
y_pred = [[1., 1.], [1., 0.]]

mae = tf.keras.losses.MeanAbsoluteError()
mae(y_true, y_pred).numpy()

0.5

#### MeanSquaredError

Computes the mean of squares of errors between labels and predictions.

```
tf.keras.losses.MeanSquaredError(
    reduction=losses_utils.ReductionV2.AUTO, name='mean_squared_error'
)
```

In [ ]:
y_true = [[0., 1.], [0., 0.]]
y_pred = [[1., 1.], [1., 0.]]

mse = tf.keras.losses.MeanSquaredError()
mse(y_true, y_pred).numpy()

0.5

#### Huber

Computes the Huber loss between `y_true` and `y_pred`.

```
tf.keras.losses.Huber(
    delta=1.0, reduction=losses_utils.ReductionV2.AUTO, name='huber_loss'
)
```

In [ ]:
y_true = [[0, 1], [0, 0]]
y_pred = [[0.6, 0.4], [0.4, 0.6]]

h = tf.keras.losses.Huber()
h(y_true, y_pred).numpy()

0.155

### Functions

#### Mean Absolute Error

Computes the mean absolute error between labels and predictions.

Main aliases:

`tf.keras.losses.MAE`, `tf.keras.losses.mae`, `tf.keras.losses.mean_absolute_error`, 

`tf.keras.metrics.MAE`, `tf.keras.metrics.mae`, 

`tf.losses.MAE`, `tf.losses.mae`, `tf.losses.mean_absolute_error`, 

`tf.metrics.MAE`, `tf.metrics.mae`, `tf.metrics.mean_absolute_error`

```
tf.keras.metrics.mean_absolute_error(
    y_true, y_pred
)
```

#### Mean Squared Error

Computes the mean squared error between labels and predictions.

Main aliases:

`tf.keras.losses.MSE`, `tf.keras.losses.mean_squared_error`, `tf.keras.losses.mse`, 

`tf.keras.metrics.MSE`, `tf.keras.metrics.mse`,

`tf.losses.MSE`, `tf.losses.mean_squared_error`, `tf.losses.mse`,

`tf.metrics.MSE`, `tf.metrics.mean_squared_error`, `tf.metrics.mse`

```
tf.keras.metrics.mean_squared_error(
    y_true, y_pred
)
```

#### Categorical Crossentropy

Computes the categorical crossentropy loss.

Main aliasses:

`tf.keras.losses.categorical_crossentropy`, `tf.losses.categorical_crossentropy`, `tf.metrics.categorical_crossentropy`

```
tf.keras.metrics.categorical_crossentropy(
    y_true, y_pred, from_logits=False, label_smoothing=0.0, axis=-1
)
```

## Nueral Model

### Define Network

#### Sequential

In [ ]:
layers = [
  tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(128, activation=tf.nn.relu),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Softmax()
]
model = tf.keras.Sequential(layers)
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_5 (Dense)             (None, 128)               100480    
                                                                 
 dense_6 (Dense)             (None, 10)                1290      
                                                                 
 softmax_2 (Softmax)         (None, 10)                0         
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10))
model.add(tf.keras.layers.Activation('softmax'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_9 (Dense)             (None, 128)               100480    
                                                                 
 dense_10 (Dense)            (None, 10)                1290      
                                                                 
 activation (Activation)     (None, 10)                0         
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


#### Functional

###  Compile Network

In [ ]:
model.compile(optimizer=✬sgd✬, loss=✬mean_squared_error✬)

SyntaxError: ignored

In [ ]:
lgorithm = SGD(lr=0.1, momentum=0.3)
model.compile(optimizer=algorithm, loss=✬mean_squared_error✬)

SyntaxError: ignored

The most common optimization algorithm is stochastic gradient descent, but Keras also
supports a suite of other state-of-the-art optimization algorithms that work well with little or
no configuration. Perhaps the most commonly used optimization algorithms because of their
generally better performance are:

❼ Stochastic Gradient Descent, or sgd, that requires the tuning of a learning rate and
momentum.

❼ Adam, or adam, that requires the tuning of learning rate.

❼ RMSprop, or rmsprop, that requires the tuning of learning rate.


### Fit Network

In [ ]:
history = model.fit(X, y, batch_size=10, epochs=100, verbose=0)

NameError: ignored

In [ ]:
model.train_on_batch(X_real, y_real)

### Save Model

In [ ]:
model.save(✬final_model.h5✬)

SyntaxError: ignored

### Load Model

In [ ]:
from keras.models import load_model
model = load_model(✬final_model.h5✬)

SyntaxError: ignored

### Evaluate Network

In [ ]:
loss, accuracy = model.evaluate(X, y)

NameError: ignored

### Make Predictions

In [ ]:
predictions = model.predict(X)

In [ ]:
predictions = model.predict_classes(X)

NameError: ignored